---
- name: Add device to group Hub
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - fortinet.fortimanager

  tasks:
    - name: Add Hub device to Hub group
      fmgr_dvmdb_group_adddev:
        adom: "root"
        group: "Hub"
        device:
          name: "Hub"
