---
- name: Add device Hub to device group Hub
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - fortinet.fortimanager

  vars:
    adom: "root"
    group_name: "Hub"
    device_name: "Hub"

  tasks:
    - name: Add device Hub to group Hub
      fmgr_dvmdb_group_adddevice:
        adom: "{{ adom }}"
        device_group: "{{ group_name }}"
        dvm_dev_list:
          - name: "{{ device_name }}"
            vdom: "root"
