---
- name: Add device to group 'Hub'
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - fortinet.fortimanager

  vars:
    adom: "root"
    group_name: "Hub"
    device_to_add:
      name: "Hub"
      vdom: "root"
      meta fields: {}

  tasks:
    - name: Add device to group Hub
      fmgr_dvmdb_group:
        adom: "{{ adom }}"
        state: present
        group:
          name: "{{ group_name }}"
          os_type: "fos"
          device-list:
            - name: "{{ device_to_add.name }}"
              vdom: "{{ device_to_add.vdom }}"
