---
- name: Install sdwan policy package on branches group
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - fortinet.fortimanager

  tasks:
    - name: Install sdwan policy package on branches
      fortinet.fortimanager.fmgr_pkg_install:
        adom: "root"
        pkg: "sdwan"
        scope:
          - name: "branches"
            vdom: "root"
